# build.sr.ht

image: debian/stable

packages:
  - default-jre-headless
  - leiningen

sources:
  - https://git.sr.ht/~rwv/ring-partial-content

tasks:
  - test: |
      cd ring-partial-content
      lein test
